// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awimhhkqdrvegricnpku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3aW1oaGtxZHJ2ZWdyaWNucGt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NzQ0MDgsImV4cCI6MjA3NDQ1MDQwOH0.lnnH04_AgKc3b-iwwrntnCH5QJxjeevsB7_fkKnnG-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});